import { useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, Check, CheckCircle2, Clock3, MapPin, Pause, Play, RotateCcw, ShieldCheck } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { workOrdersApi } from "../../api/workOrders";
import { errorMessage } from "../../api/client";
import type { Checklist, ExecutionSummary } from "../../types/api";
import StatusPill from "../../components/StatusPill";

const getPosition = () => new Promise<{ latitude: number; longitude: number }>((resolve, reject) => {
  if (!navigator.geolocation) return reject(new Error("Location is unavailable on this device."));
  navigator.geolocation.getCurrentPosition((p) => resolve({ latitude: p.coords.latitude, longitude: p.coords.longitude }), () => reject(new Error("Location permission is required to record execution evidence.")), { enableHighAccuracy: true, timeout: 10000 });
});

export default function CrewWorkOrderPage() {
  const { id = "" } = useParams();
  const [summary, setSummary] = useState<ExecutionSummary | null>(null), [checklists, setChecklists] = useState<Checklist[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null), [pauseReason, setPauseReason] = useState("Operational hold"), [notes, setNotes] = useState("");
  const load = () => Promise.all([workOrdersApi.summary(id), workOrdersApi.checklists(id)]).then(([s,c]) => { setSummary(s); setChecklists(c); }).catch((e) => setError(errorMessage(e)));
  useEffect(() => { void load(); }, [id]);
  async function run(action: () => Promise<unknown>) { setBusy(true); setError(null); try { await action(); await load(); } catch(e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  async function toggle(list: Checklist, itemId: string, value: boolean) { await run(() => workOrdersApi.updateChecklist(list.id, itemId, value)); }
  if (!summary) return <div className="portal-page"><Link className="back-link" to="/crew"><ArrowLeft size={16} /> My work</Link><div className="empty-card">{error || "Loading work instructions…"}</div></div>;
  const o = summary.work_order;
  const checked = (list: Checklist, item: string) => { const v = list.completed_items[item]; return typeof v === "boolean" ? v : Boolean(v?.value); };
  return <div className="portal-page mobile-work"><Link className="back-link" to="/crew"><ArrowLeft size={16} /> My work</Link><div className="portal-page-heading compact"><div><span className="eyebrow">FIELD WORK ORDER</span><h1>{o.work_order_number}</h1><p>{o.title}</p></div><StatusPill value={o.status} /></div>{error && <div className="form-error">{error}</div>}
    <section className="instruction-grid"><article><small>WHAT</small><h3>{summary.what.activity}</h3><p>{summary.what.instructions}</p></article><article><small>WHERE</small><h3><MapPin size={18} /> {summary.where.section_id}</h3><p>Asset {summary.where.asset_id}</p></article><article><small>WHEN</small><h3><Clock3 size={18} /> {summary.when.planned_start ? new Date(summary.when.planned_start).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "—"}</h3><p>Finish by {summary.when.planned_end ? new Date(summary.when.planned_end).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" }) : "—"}</p></article><article><small>HOW</small><h3><ShieldCheck size={18} /> Follow possession controls</h3><p>{summary.how.safety_requirements}</p></article></section>
    {o.status === "ASSIGNED" && <button className="primary action-button" disabled={busy} onClick={() => void run(() => workOrdersApi.acknowledge(id))}><Check size={18} /> Acknowledge work order</button>}
    <section className="panel-card"><div className="section-heading"><div><span className="eyebrow">MANDATORY CONTROL</span><h2>Execution checklists</h2><p>Safety items must be completed and signed before work can start.</p></div><ShieldCheck /></div><div className="checklist-stack">{checklists.map((list) => <article key={list.id}><div className="checklist-title"><span><b>{list.type}</b><small>{list.is_mandatory ? "Mandatory" : "Supporting"}</small></span>{list.signed_at && <span className="signed"><CheckCircle2 size={15} /> Signed</span>}</div>{list.items.map((item) => <label key={item.id} className="check-row"><input type="checkbox" checked={checked(list, item.id)} disabled={busy || Boolean(list.signed_at)} onChange={(e) => void toggle(list, item.id, e.target.checked)} /><span>{item.text}{item.required && <em>Required</em>}</span></label>)}{!list.signed_at && <button className="small-button" disabled={busy || (list.is_mandatory && list.items.some((i) => i.required && !checked(list, i.id)))} onClick={() => void run(() => workOrdersApi.signOff(list.id))}><Check size={14} /> Sign off</button>}</article>)}</div></section>
    <section className="panel-card execution-controls"><span className="eyebrow">LIVE EXECUTION</span><h2>Record actual work status</h2>{o.status === "ACKNOWLEDGED" && <button className="primary action-button" disabled={busy} onClick={() => void run(async () => { const p = await getPosition(); return workOrdersApi.start(id, p.latitude, p.longitude); })}><Play size={18} /> Start work with location</button>}{o.status === "IN_PROGRESS" && <div className="control-row"><input value={pauseReason} onChange={(e) => setPauseReason(e.target.value)} aria-label="Pause reason" /><button className="secondary" disabled={busy} onClick={() => void run(() => workOrdersApi.pause(id, pauseReason))}><Pause size={17} /> Pause</button></div>}{o.status === "PAUSED" && <button className="primary action-button" disabled={busy} onClick={() => void run(() => workOrdersApi.resume(id))}><RotateCcw size={18} /> Resume work</button>}{o.status === "IN_PROGRESS" && <div className="completion-box"><label>Completion notes<textarea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Describe work completed and any field observation" /></label><button className="primary action-button" disabled={busy} onClick={() => void run(async () => { const p = await getPosition(); return workOrdersApi.complete(id, { ...p, notes, photos: [] }); })}><CheckCircle2 size={18} /> Complete with location evidence</button></div>}{["COMPLETED","VERIFIED"].includes(o.status) && <div className="success-message"><CheckCircle2 /><span><b>Field execution recorded</b><small>{o.status === "VERIFIED" ? "Supervisor verification complete." : "Awaiting supervisor verification."}</small></span></div>}{o.status === "REJECTED" && <div className="warning-message"><AlertTriangle /><span><b>Verification rejected</b><small>{o.rejection_reason || "Review supervisor comments."}</small></span></div>}</section>
  </div>;
}
