import { useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, CheckCircle2, ClipboardCheck, HardHat, MapPin, ShieldCheck, UserCheck } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { workOrdersApi } from "../../api/workOrders";
import { errorMessage } from "../../api/client";
import type { CrewMember, ExecutionSummary } from "../../types/api";
import StatusPill from "../../components/StatusPill";

export default function WorkOrderAssignmentPage() {
  const { id = "" } = useParams();
  const [summary, setSummary] = useState<ExecutionSummary | null>(null), [crew, setCrew] = useState<CrewMember[]>([]), [selected, setSelected] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null);
  const load = () => Promise.all([workOrdersApi.summary(id), workOrdersApi.activeCrew()]).then(([s,c]) => { setSummary(s); setCrew(c); }).catch((e) => setError(errorMessage(e)));
  useEffect(() => { void load(); }, [id]);
  async function assign() { if (!selected) return; setBusy(true); setError(null); try { await workOrdersApi.assign(id, selected); await load(); } catch(e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  if (!summary) return <div className="portal-page"><Link className="back-link" to="/admin/work-orders"><ArrowLeft size={16} /> Work orders</Link><div className="empty-card">{error || "Loading execution evidence…"}</div></div>;
  const o = summary.work_order, reference = o.department_id || o.contract_id || o.amc_id || o.oem_service_id || "Reference not recorded";
  return <div className="portal-page"><Link className="back-link" to="/admin/work-orders"><ArrowLeft size={16} /> Work orders</Link><div className="portal-page-heading compact"><div><span className="eyebrow">APPROVED PLAN → ACCOUNTABLE EXECUTION</span><h1>{o.work_order_number}</h1><p>{o.title} · {o.plan_id} · {o.maintenance_id}</p></div><StatusPill value={o.status} /></div>{error && <div className="form-error">{error}</div>}
    <section className="detail-band"><div><MapPin /><span><small>WHERE</small><b>{o.section_id}</b><em>{o.asset_id}</em></span></div><div><ClipboardCheck /><span><small>WHAT</small><b>{o.required_skill} maintenance</b><em>{o.priority} priority</em></span></div><div><HardHat /><span><small>WHO / MODE</small><b>{o.execution_mode.replaceAll("_", " ")}</b><em>{reference}</em></span></div><div><ShieldCheck /><span><small>WHEN</small><b>{o.planned_start ? new Date(o.planned_start).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "—"}</b><em>{o.estimated_duration_min} min planned</em></span></div></section>
    <div className="two-column assignment-grid"><section className="panel-card"><div className="section-heading"><div><span className="eyebrow">EXECUTION READINESS</span><h2>{summary.execution_status.executable ? "Ready to execute" : "Blocked until evidence is complete"}</h2></div>{summary.execution_status.executable ? <CheckCircle2 className="success-icon" /> : <AlertTriangle className="warning-icon" />}</div><div className="readiness-list">{[["Approval",summary.execution_status.approval_status === "APPROVED"],["Safety constraints",Boolean(summary.execution_status.safety_validation?.valid)],["Manpower",summary.resources.manpower_available],["Equipment",summary.resources.equipment_available],["Materials",summary.resources.materials_available]].map(([label,ok]) => <div key={String(label)} className={ok ? "ready" : "blocked"}>{ok ? <CheckCircle2 /> : <AlertTriangle />}<span>{label}</span><b>{ok ? "Ready" : "Pending"}</b></div>)}</div>{summary.execution_status.recommendation_reasons?.length > 0 && <div className="reason-box"><b>Backend readiness reasons</b>{summary.execution_status.recommendation_reasons.map((r) => <p key={r}>• {r}</p>)}</div>}</section>
      <section className="panel-card"><div className="section-heading"><div><span className="eyebrow">MANUAL ACCOUNTABILITY</span><h2>Assign active crew</h2><p>Choose a candidate. The backend—not React—validates skill, shift, availability and provider affiliation.</p></div><UserCheck /></div>{o.status === "DRAFT" ? <><label className="field-label">Active crew member<select value={selected} onChange={(e) => setSelected(e.target.value)}><option value="">Select an active crew member</option>{crew.map((c) => <option key={c.employee_id} value={c.employee_id}>{c.full_name} · {c.employee_id} · {c.primary_skill} · {c.availability || "UNKNOWN"}{c.department_id ? ` · ${c.department_id}` : ""}{c.provider_id ? ` · ${c.provider_id}` : ""}</option>)}</select></label>{crew.length === 0 && <div className="reason-box warning"><b>No active crew returned by the backend</b><p>Approve a crew account before assigning this work order.</p></div>}<div className="backend-rule"><ShieldCheck size={16} /><span><b>Backend validation is authoritative</b><small>Invalid skill, shift, availability or affiliation is rejected by the assignment API.</small></span></div><button className="primary full-button" disabled={!selected || busy} onClick={() => void assign()}>{busy ? "Validating with backend…" : "Assign work and notify"}<UserCheck size={17} /></button></> : <div className="assigned-person"><CheckCircle2 /><span><small>ASSIGNED CREW</small><b>{summary.who.crew?.name || "Assigned"}</b><em>{summary.who.crew?.employee_id || o.assigned_crew_id}</em></span></div>}</section></div>
    <section className="panel-card"><span className="eyebrow">AUTOMATIC NOTIFICATION CONTENT</span><h2>What the selected crew member receives</h2><div className="notification-preview"><div><small>WHAT</small><b>{summary.what.activity}</b><span>{summary.what.instructions}</span></div><div><small>WHERE</small><b>{summary.where.section_id} · {summary.where.asset_id}</b></div><div><small>WHEN</small><b>{summary.when.planned_start ? new Date(summary.when.planned_start).toLocaleString("en-IN") : "—"}</b></div><div><small>HOW</small><b>{summary.how.safety_requirements}</b><span>{summary.how.instructions}</span></div></div></section>
  </div>;
}
